#!/usr/bin/env bash
#Display the content of the file /etc/passwd, using the while loop + IFS
FILENAME="/etc/passwd"
while IFS=: read -r username password userid groupid comment homedir cmdshell
do
	echo "The user $username is part of the $groupid gang, lives in $homedir and rides $cmdshell. $username's place is protected by the passcode $password, more info about the user here: $comment"
done < $FILENAME
