#!/usr/bin/env bash
#Process and PID file
touch /var/run/myscript.pid
pgrep -f /var/run/myscript.pid > /var/run/archivotemp
cp /var/run/archivotemp /var/run/myscript.pid
rm /var/run/archivotemp

trap "echo I hate the kill command; rm /var/run/myscript.pid; pkill -f /var/run/myscript.pid" SIGTERM
trap "echo Y U no love me ?!" SIGINT
trap "rm /var/run/myscript.pid; pkill -f /var/run/myscript.pid" SIGQUIT

while true
do
		printf "%s\n" "To infinity and beyond"
	done
