#!/usr/bin/env bash
#Process and PID file
echo $$ > /var/run/myscript.pidZZ
while true
do
		echo To infinity and beyond
			trap -arg SIGTERM
		echo I hate the kill command
			trap -arg SIGINT
		echo Y U no love me?!
			trap -arg SIGQUIT SIGTERM
				rm /var/run/myscript.pid
				kill $"(pgrep -f .//var/run/myscript.pid)"
done
