#!/usr/bin/env bash
#Process and PID file
touch /var/run/myscript.pid
pgrep -f /var/run/myscript.pid > /var/run/myscript.pid
while true
do
		echo To infinity and beyond
			trap -arg SIGTERM
		echo I hate the kill command
			trap -arg SIGINT
		echo Y U no love me?!
				rm /var/run/myscript.pid
done
